return {
	ws_send = 'ws_send',
	set_power_tokens = 'set_power_tokens',
	player_panel_click = 'player_panel_click',
	house_card_selected = 'house_card_selected',
	leave_power_token_click = 'leave_power_token_click',
	map_resolve_order = 'map_resolve_order',
	march_select_army_ok_button_click = 'march_select_army_ok_button_click',
	map_target_selected = 'map_target_selected',
	partial_march_remove = 'partial_march_remove',
	hints_goto_button_click = 'hints_goto_button_click',
	hints_next_button_click = 'hints_next_button_click',
	map_show_orders_menu = 'map_show_orders_menu',
	order_button_click = 'order_button_click',
	ws_add_order = 'ws_add_order',
	ws_open_orders = 'ws_open_orders',
	raven_card_or_order_click = 'raven_card_or_order_click',
	ws_raven_card_or_order = 'ws_raven_card_or_order',
}