local tracks = require "main/ui/tracks"
local top_panel = require "main/ui/top_panel"
local orders = require "main/ui/orders"
local login = require "main/ui/login/debug_login"

local ws = require "main/messaging/websocket"
local mes_poc = require "main/messaging/message_processing"

function init(self)
	msg.post(".", "acquire_input_focus")
	login:init()

	ws:init()
	mes_poc.set_set_tracks_cb(tracks, tracks.set_tracks)
	mes_poc.set_set_game_state_cb(top_panel, top_panel.set_game_state)

	self.tracks_open = false
	-- self.me = "kraken"
	-- self.players = {
	-- 	moose = { id = -1, name = "Waiting for player..." },
	-- 	lion = { id = -1, name = "Waiting for player..." },
	-- 	wolf = { id = -1, name = "Waiting for player..." },
	-- 	pufferfish = { id = -1, name = "Waiting for player..." },
	-- 	kraken = { id = -1, name = "Waiting for player..." },
	-- 	rose = { id = -1, name = "Waiting for player..." }
	-- }
	tracks:init()
	top_panel:init()
	orders:init()
	--tracks:set_tracks(self.tracks)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if message_id == hash("touch_multi") then
		local text = ""
		local sum = vmath.vector3()
		if #message.touch > 1 then
			sum = vmath.vector3(message.touch[1].dx + message.touch[2].dx, message.touch[1].dy + message.touch[2].dy, 0)
		end
		for i, touchdata in ipairs(message.touch) do
			text = text .. "point " .. i .. ' x ' .. touchdata.x .. ' y ' .. touchdata.y .. ' dx ' .. touchdata.dx .. ' dy ' .. touchdata.dy .. "\n"
		end
		text = text .. 'sum of deltas ' .. sum
		local s = gui.get_node("debug")
		gui.set_text(s, text)
	elseif message_id == hash("show_orders_menu") then
		orders:open(message.label, message.deleted)
	end
end


function on_input(self, action_id, action)
	if login:on_input(action_id, action) then
		return true
	end
	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(tracks.tracks, action.x, action.y) then
			if tracks.is_open then
				tracks:close()
				-- close_tracks(self, tracks)
			else
				tracks:open()
				-- open_tracks(self, tracks)
			end	
		elseif orders:get_button_pressed(action.x, action.y) then
			orders:add_order_to_map()
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
