local tracks = require "main/ui/tracks"
local top_panel = require "main/ui/top_panel"
local orders = require "main/ui/orders"
local login = require "main/ui/login/debug_login"
local supply_panel = require "main/ui/supply_panel"
local hints = require "main/ui/hints"

local ws = require "main/messaging/websocket"
local mes_poc = require "main/messaging/message_processing"
local action_proc = require "main/ui/messaging/action_reply_processing"

local function register_callbacks()
	mes_poc:set_set_tracks_cb(function(tracks_data)
		tracks:set_tracks(tracks_data)
	end)
	mes_poc:set_set_game_state_cb(function(game_state)
		top_panel:set_game_state(game_state)
	end)
	mes_poc:set_set_players_cb(function(players)
		tracks:set_players(players)
	end)
	mes_poc:set_calc_stars_available_cb(function(court_track)
		orders:calc_stars_available(court_track)
	end)
	mes_poc:set_show_orders_on_map_cb(function(orders_)
		orders:show_orders_on_map(orders_)
	end)
	mes_poc:set_set_addOrder_hints_cb(function(my_armies, my_orders)
		hints:set_addOrder_hints(my_armies, my_orders)
	end)


	mes_poc:set_set_supply_usage_rules_cb(function(supplyUsageRules)
		supply_panel:set_supply_usage_rules(supplyUsageRules)
	end)
	-- supply_panel:set_supply_usage_rules(message.gameRules.supplyUsage)
	supply_panel:set_available(message.gameState.supplies[game_data.me])
	supply_panel:set_current(message.gameState.supplies[game_data.me])
	local my_armies = filter_my_armies(message.gameState.armies)
	supply_panel:update_usage(my_armies)
end

function init(self)
	msg.post(".", "acquire_input_focus")
	login:init()

	ws:init()
	
	register_callbacks()

	self.tracks_open = false

	tracks:init()
	top_panel:init()
	orders:init()
	supply_panel:init()
	hints:init()
	--tracks:set_tracks(self.tracks)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if message_id == hash("touch_multi") then
		local text = ""
		local sum = vmath.vector3()
		if #message.touch > 1 then
			sum = vmath.vector3(message.touch[1].dx + message.touch[2].dx, message.touch[1].dy + message.touch[2].dy, 0)
		end
		for i, touchdata in ipairs(message.touch) do
			text = text .. "point " .. i .. ' x ' .. touchdata.x .. ' y ' .. touchdata.y .. ' dx ' .. touchdata.dx .. ' dy ' .. touchdata.dy .. "\n"
		end
		text = text .. 'sum of deltas ' .. sum
		local s = gui.get_node("debug")
		gui.set_text(s, text)
	elseif message_id == hash("show_orders_menu") then
		if message.deleted then
			hints:set_has_order(message.tile_num, false)
		end
		orders:open(message.label, message.tile_num, message.name, message.deleted)
	end
end


function on_input(self, action_id, action)
	if login:on_input(action_id, action) then
		return true
	end
	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(tracks.tracks, action.x, action.y) then
			if tracks.is_open then
				tracks:close()
				-- close_tracks(self, tracks)
			else
				tracks:open()
				-- open_tracks(self, tracks)
			end	
		elseif orders:get_button_pressed(action.x, action.y) then
			local order = orders:get_order_to_send()
			hints:set_has_order(order.player_action.tileNumber, true)
			ws.send(order)
			orders:add_order_to_map()
		elseif hints:get_button_pressed(action.x, action.y) then
			return true
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
