local tracks = require "main/ui/tracks"
local ws = require "main/ui/websocket"

function init(self)
	msg.post(".", "acquire_input_focus")

	ws:init()
	
	self.tracks_open = false
	self.me = "lion"
	self.tracks = { 
		throne = {
			"moose",
			"lion",
			"wolf",
			"pufferfish",
			"kraken",
			"rose"
		},
		fiefdoms = {
			"kraken",
			"rose",
			"pufferfish",
			"wolf",
			"moose",
			"lion"
		},
		court = {
			"lion",
			"wolf",
			"pufferfish",
			"moose",
			"rose",
			"kraken"
		}
	}
	self.players = {
		moose = { id = 1, name = "player1" },
		lion = { id = 2, name = "player2" },
		wolf = { id = 3, name = "player3" },
		pufferfish = { id = 4, name = "player4" },
		kraken = { id = 5, name = "player5" },
		rose = { id = 6, name = "player6" }
	}
	tracks:init(self.me, self.players)
	tracks:set_tracks(self.tracks)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if message_id == hash("touch_multi") then
		local text = ""
		local sum = vmath.vector3()
		if #message.touch > 1 then
			sum = vmath.vector3(message.touch[1].dx + message.touch[2].dx, message.touch[1].dy + message.touch[2].dy, 0)
		end
		for i, touchdata in ipairs(message.touch) do
			text = text .. "point " .. i .. ' x ' .. touchdata.x .. ' y ' .. touchdata.y .. ' dx ' .. touchdata.dx .. ' dy ' .. touchdata.dy .. "\n"
		end
		text = text .. 'sum of deltas ' .. sum
		local s = gui.get_node("debug")
		gui.set_text(s, text)
	end
end


function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(tracks.tracks, action.x, action.y) then
			if tracks.is_open then
				tracks:close()
				-- close_tracks(self, tracks)
			else
				tracks:open()
				-- open_tracks(self, tracks)
			end	
		end
	end
end

-- function open_tracks(self, tracks)
-- 	gui.animate(tracks, "position.y", 260, gui.PLAYBACK_ONCE_FORWARD, ANIMATION_TIME)
-- 	gui.animate(gui.get_node("t_under_shiled_u1"), "color.w", 1, gui.PLAYBACK_ONCE_FORWARD, ANIMATION_TIME)
-- 	gui.animate(gui.get_node("t1"), "scale", 1, gui.PLAYBACK_ONCE_FORWARD, ANIMATION_TIME)
-- 	gui.animate(gui.get_node("t1"), "position.y", 175, gui.PLAYBACK_ONCE_FORWARD, ANIMATION_TIME)
-- 	self.tracks_open = true
-- end

-- function close_tracks(self, tracks)
-- 	gui.animate(tracks, "position.y", -100, gui.PLAYBACK_ONCE_FORWARD, ANIMATION_TIME)
-- 	gui.animate(gui.get_node("t_under_shiled_u1"), "color.w", 0, gui.PLAYBACK_ONCE_FORWARD, ANIMATION_TIME)
-- 	gui.animate(gui.get_node("t1"), "scale", .7, gui.PLAYBACK_ONCE_FORWARD, ANIMATION_TIME)
-- 	gui.animate(gui.get_node("t1"), "position.y", 185, gui.PLAYBACK_ONCE_FORWARD, ANIMATION_TIME)
-- 	self.tracks_open = false
-- end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
