services:
  redis:
    image: redis:7.2.2
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - net1
  mysql:
    image: "mysql:8.0.34"
    environment:
      MYSQL_ROOT_PASSWORD: "rootPassword"
      MYSQL_DATABASE: "fwc"
      MYSQL_USER: "bpuser"
      MYSQL_PASSWORD: "123456"
    networks:
      - net1
    volumes:
      - database_volume:/var/lib/mysql
  web-server:
    image: "web_server_prod"
    working_dir: "/web-server"
    build:
      context: ./web-server
      dockerfile: ./Dockerfile
    restart: always
    command: ["node", "dist/src/main.js"]
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - REDIS_URL=redis://redis:6379
      - SERVER_PORT=80
      - SERVER_NAME=server1
    networks:
      - net1
  worker:
    restart: on-failure
    image: worker_prod
    build:
        context: ./
        dockerfile: ./game-logic-core/docker/Dockerfile_prod
    working_dir: "/fwc"
    environment:
      - REDIS_HOST=redis
      - WORKER_NAME=worker1
    command: ["java", "-Xrs", "-jar", 'worker.jar']
    networks:
      - net1
    depends_on:
      - redis
  reverse_proxy:
    image: "nginx_prod"
    restart: on-failure
    build:
        context: ./
        dockerfile: ./nginx.conf.d/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - net1


networks:
  net1:
volumes:
    database_volume:
