version: "3.8"

services:
  redis:
    image: redis:7.2.2
    #restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - net1
  mysql:
    image: "mysql:8.0.34"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootPassword"
      MYSQL_DATABASE: "fwc"
      MYSQL_USER: "bpuser"
      MYSQL_PASSWORD: "123456"
    networks:
      - net1
  web-server:
    image: "node:18"
    ports: 
      - "3001:80"
      - "9229:9229"
    volumes:
      - "./web-server:/web-server"
    working_dir: "/web-server"
    command: ["npx", "nest", "start", "--debug=0.0.0.0:9229", "--watch"]
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - REDIS_URL=redis://redis:6379
      - SERVER_PORT=80
      - TESTING=true
    networks:
      - net1
  react:
    image: "node:18"
    ports:
      - "3000:3000"
      - "9228:9228"
    volumes:
      - "./front-login:/front-login"
    working_dir: "/front-login"
    depends_on:
      - "web-server"
    command: ["npm", "run", "start", "--debug=0.0.0.0:9228"]
    networks:
      - net1
  worker:
    image: "sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.10_7_1.9.9_2.12.19"
    restart: on-failure
    volumes:
      - "./game-logic-core:/fwc"
    working_dir: "/fwc"
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=redis
      - WORKER_NAME=worker1
    command: ["sbt", "run", "--", "-Xrs"]
    networks:
      - net1
    depends_on:
      - redis
  reverse_proxy:
    image: "nginx:1.25.4"
    volumes:
      - ./nginx.conf.d/fwc.conf:/etc/nginx/nginx.conf
      - ./front-defold/build/:/www/data/html
      - ./homepage:/www/data/homepage
    ports:
      - "8888:80"
    networks:
      - net1
    depends_on:
      - web-server

networks:
  net1:
