#!/usr/bin/python3
import os
import sys
import subprocess
import argparse

parser = argparse.ArgumentParser('Table games production builder.')
parser.add_argument('-o', '--only', nargs='+', choices=['worker', 'nest', 'login', 'defold', 'nginx']
                    , action='store', help='Build only selected projects; {worker} - game-logic-core - Scala project,'
                                           + '{nest} - Nest.js http and WS server,'
                                           + '{login} - front-login React front-end project,'
                                           + '{defold} - front-defold - Defold game GUI.'
                                           + '{nginx} - nGinx web server - this option is used in --save-only')
parser.add_argument('-nd', '--no-docker-build', action='store_true', help='Don\'t run "docker compose build".')
parser.add_argument('-s', '--save', action='store_true', help='Save docker images to the \'build\' directory.')
parser.add_argument('-so', '--save-only', action='store_true', help='Do not build anything, only save previously '
                                                                    'built images.')
args = parser.parse_args()


def start():
    proj_root = get_project_path()
    is_error = False
    is_nest_error = False
    is_worker_error = False
    is_static_content_error = False

    if not os.path.exists("../init/.cache") or not os.path.exists("../init/.cache/bob.jar"):
        print_error("Run the init script before running this script.")
        exit(1)

    if not args.save_only and (not args.only or 'worker' in args.only):
        print_header('Building the worker...')
        result = subprocess.run(['docker', 'run', '--rm',
                                 '-v', proj_root + '/game-logic-core:/fwc',
                                 '-w', '/fwc',
                                 'sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.10_7_1.9.9_2.12.19',
                                 'sbt', 'assembly'])
        if result.returncode != 0:
            print_error('Worker build failed.')
            is_worker_error = True
        else:
            print_success('The worker jar was built successfully.')

    if not args.save_only and (not args.only or 'nest' in args.only):
        print_header("Transpiling the web server...")
        result = subprocess.run(['docker', 'run', '--rm',
                                 '-v', proj_root + "/web-server:/web-server",
                                 '-w', '/web-server',
                                 'node:18',
                                 'npx', 'nest', 'build'])
        if result.returncode != 0:
            print_error('Web server transpiling failed.')
            is_nest_error = True
        else:
            print_success('Web server transpiling was successful.')

    if not args.save_only and (not args.only or 'login' in args.only):
        print_header("Building React front-end...")
        result = subprocess.run(['docker', 'run', '--rm',
                                 '-v', proj_root + "/front-login:/front-login",
                                 '-w', '/front-login',
                                 'node:18',
                                 'npx', 'react-scripts', 'build'])
        if result.returncode != 0:
            print_error('Building React front-end failed.')
            is_static_content_error = True
        else:
            print_success('Building React front-end was successful.')

    if not args.save_only and (not args.only or 'defold' in args.only):
        print_header("Building Defold front-end...")
        result = subprocess.run(['docker', 'run', '--rm',
                                 '-v', proj_root + "/front-defold:/fd_fwc",
                                 '-v', proj_root + '/tools/init/.cache:/bob',
                                 '-w', '/fd_fwc',
                                 'sbt_xrandr',
                                 'java', '-jar', '/bob/bob.jar',
                                 '--settings=web.properties',
                                 '-bo', '/fd_fwc/build/prod/htmlLaunchDir',
                                 'build', 'bundle', '-p', 'js-web', '-a'])

        if result.returncode != 0:
            print_error('Building Defold front-end failed.')
            is_static_content_error = True
        else:
            print_success('Building Defold front-end was successful.')

    if not args.save_only and not args.no_docker_build:
        print_header("Building docker images...")
        result = subprocess.run(['docker', 'compose', 'build'])
        if result.returncode != 0:
            print_error('Building docker images failed.')
            is_error = True
        else:
            print_success('Building docker images was successful.')

    if args.save or args.save_only:
        if not os.path.exists("../../build"):
            os.mkdir("../../build")
        print_header("Zipping and saving the docker images to the 'build' directory...\n")

        if is_nest_error:
            print_warning("There was an error building the Nest.js server, skipping...")
        elif not args.only or 'nest' in args.only:
            print_header("Saving Web Server...")
            with open('../../build/web_server.tar.gz', 'w') as outfile:
                save = subprocess.run(['docker', 'save', 'web_server_prod'], check=True, capture_output=True)
                result = subprocess.run(["gzip"], input=save.stdout, stdout=outfile)
                if result.returncode != 0:
                    print_error('Saving Web Server docker image failed.')
                    is_error = True
                else:
                    print_success('Saving Web Server docker image was successful.')

        if is_worker_error:
            print_warning("There was an error building the worker, skipping...")
        elif not args.only or 'worker' in args.only:
            print_header("Saving Worker...")
            with open('../../build/worker.tar.gz', 'w') as outfile:
                save = subprocess.run(['docker', 'save', 'worker_prod'], check=True, capture_output=True)
                result = subprocess.run(['gzip'], input=save.stdout, stdout=outfile)
                if result.returncode != 0:
                    print_error('Saving Worker docker image failed.')
                    is_error = True
                else:
                    print_success('Saving Worker docker image was successful.')

        if is_static_content_error:
            print_warning("There was an error building the static web content, skipping...")
        elif not args.only or 'defold' in args.only or 'login' in args.only or 'nginx' in args.only:
            print_header("Saving Nginx...")
            with open('../../build/nginx.tar.gz', 'w') as outfile:
                save = subprocess.run(['docker', 'save', 'nginx_prod'], check=True, capture_output=True)
                result = subprocess.run(['gzip'], input=save.stdout, stdout=outfile)
                if result.returncode != 0:
                    print_error('Saving Nginx docker image failed.')
                    is_error = True
                else:
                    print_success('Saving Nginx docker image was successful.')

    if is_error or is_worker_error or is_static_content_error or is_nest_error:
        print_error("There was an error in the process! Check what went wrong and rerun.")
        exit(1)


if __name__ == '__main__' and not __package__:
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    sys.path.append('../../')
    __package__ = 'tools.builder'

    from ..common.colors import print_error, print_success, print_header, print_info, print_warning
    from ..common.utils import get_project_dir_name, get_project_path

    start()
