local labels = require "main/labels"


local function draw_line(from, to)
	msg.post("@render:", "draw_line", { start_point = from, end_point = to, color = vmath.vector4(1,0,0,1) })
end

function init(self)
	msg.post("#camera", "acquire_camera_focus")
	msg.post(".", "acquire_input_focus")

	self.camera_move_dir = vmath.vector3()
	self.camera_drag_delta = vmath.vector3()
	self.camera_move_speed = 1000
	self.moving_camera = false

	self.camera_up_limit = vmath.vector3(0, 950, 0)
	self.camera_down_limit = vmath.vector3(0, -850, 0)

	-- self.camera_up_limit = vmath.vector3(2000, 2000, 0)
	-- self.camera_down_limit = vmath.vector3(-1000, -2000, 0)

	self.zoom = 1
	
	self.mouse_pressed = false
	self.try_selecting = false

	self.to = vmath.vector3()

	labels:init()
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	if self.moving_camera then
		local pos = go.get_position()         
		pos = pos + self.camera_move_dir * self.camera_move_speed * dt
		pos = pos - self.camera_drag_delta
		if pos.x < self.camera_down_limit.x then
			pos.x = self.camera_down_limit.x
		elseif pos.x > self.camera_up_limit.x then
			pos.x = self.camera_up_limit.x
		end
		if pos.y < self.camera_down_limit.y then
			pos.y = self.camera_down_limit.y
		elseif pos.y > self.camera_up_limit.y then
			pos.y = self.camera_up_limit.y
		end
		go.set_position(pos)                  
	end
	
	if self.try_selecting then
		local camera_pos = go.get_position()
		local to = self.to + camera_pos
		local from1 = to + vmath.vector3(0, 28, 0)
		local from2 = to + vmath.vector3(0, -28, 0)

		local result1 = physics.raycast(from1, to, { hash("label") })
		local result2 = physics.raycast(from2, to, { hash("label") })
		-- if result1 and result1 == result2 then
		if result1 and result2 and result1.id == result2.id then
			msg.post(result1.id, 'select')
			-- draw_line(from1, result1.position)
			-- draw_line(from2, result2.position)
		end
		self.try_selecting = false
	end

	self.moving_camera = false
	self.camera_move_dir = vmath.vector3()
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

local function add_zoom(self)
	if self.zoom >= 2 then
		return 2
	else 
		self.zoom = self.zoom + .1
		return self.zoom
	end
end

local function reduce_zoom(self)
	if self.zoom <= .5 then
		return .5
	else 
		self.zoom = self.zoom - .1
		return self.zoom
	end
end

function on_input(self, action_id, action)
	if action_id == hash("camera_up") then
		self.camera_move_dir.y = 1                       
	elseif action_id == hash("camera_down") then
		self.camera_move_dir.y = -1
	elseif action_id == hash("camera_left") then
		self.camera_move_dir.x = -1
	elseif action_id == hash("camera_right") then
		self.camera_move_dir.x = 1
	elseif action_id == hash("touch") and action.pressed then
		self.to.x = action.x
		self.to.y = action.y
		self.mouse_pressed = true
		self.try_selecting = true
	elseif action_id == hash("touch") and self.mouse_pressed and (action.dx ~= 0 or action.dy ~= 0) and not action.released then
		self.moving_camera = true
		self.camera_drag_delta = vmath.vector3(action.dx, action.dy, 0)
	elseif action_id == hash("touch") and action.released then
		self.mouse_pressed = false
	-- elseif action_id == hash("zoom_in") then
	-- 	go.animate("/map", "scale", go.PLAYBACK_ONCE_FORWARD, add_zoom(self), go.EASING_LINEAR, .5)
	-- elseif action_id == hash("zoom_out") then
	-- 	go.animate("/map", "scale", go.PLAYBACK_ONCE_FORWARD, reduce_zoom(self), go.EASING_LINEAR, .5)
	end

	if vmath.length(self.camera_move_dir) > 0 then
		self.moving_camera = true
		self.dir = vmath.normalize(self.camera_move_dir) 
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
