local utils = require "main/utils"

local CAMERA_LIMITS = {
	up = vmath.vector3(150, 950, 0),
	down = vmath.vector3(-150, -870, 0)
}

local SCREEN_SIZE = vmath.vector3(1200, 675, 0)

local function update_camera_limits(self)
	self.camera_up_limit = vmath.vector3(
	CAMERA_LIMITS.up.x + ((CAMERA_LIMITS.up.x + SCREEN_SIZE.x) * (self.zoom - 1)),
	-- SCREEN_SIZE.x * (self.zoom - 1),
	CAMERA_LIMITS.up.y + ((CAMERA_LIMITS.up.y + SCREEN_SIZE.y) * (self.zoom - 1)),
	0)
	self.camera_down_limit = vmath.vector3(
	CAMERA_LIMITS.down.x + (CAMERA_LIMITS.down.x * (self.zoom - 1)),
	-- 0, 
	CAMERA_LIMITS.down.y + (CAMERA_LIMITS.down.y * (self.zoom - 1)), 
	0)
end

local function set_map_scale(self, zoom)
	self.zoom = zoom or self.zoom
	go.set_scale(vmath.vector3(self.zoom, self.zoom, 1), "/map")
end

function init(self)
	msg.post("#camera", "acquire_camera_focus")
	-- msg.post(".", "acquire_input_focus")

	self.camera_move_dir = vmath.vector3()
	self.camera_drag_delta = vmath.vector3()
	self.camera_move_speed = 1000
	self.moving_camera = false

	self.camera_up_limit = CAMERA_LIMITS.up
	self.camera_down_limit = CAMERA_LIMITS.down

	-- self.camera_up_limit = vmath.vector3(2000, 2000, 0)
	-- self.camera_down_limit = vmath.vector3(0, -2000, 0)

	set_map_scale(self, 1.4)
	update_camera_limits(self)
	
	self.mouse_pressed = false
	self.try_selecting = false

	self.to = vmath.vector3()

	self.mouse_last_pos = vmath.vector3()

	self.m_touch = {}
	self.zoom_delay = 0
	print(msg.url())
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

local function try_selecting(self, group, size)
	local camera_pos = go.get_position()
	local to = (self.to + camera_pos)
	local from1 = to + vmath.vector3(0, size * self.zoom, 0)
	local from2 = to + vmath.vector3(0, -1 * size * self.zoom, 0)

	local result1 = physics.raycast(from1, to, { hash(group) })
	local result2 = physics.raycast(from2, to, { hash(group) })
	if result1 and result2 and result1.id == result2.id then
		msg.post("/map", 'select_label', {
			id = result1.id
		})
		--msg.post("/gui", "print_debug", { text = tostring(result1.id)})
		return true
	end
	return false
end


local function impose_camera_limits(self, pos)
	if pos.x < self.camera_down_limit.x then
		pos.x = self.camera_down_limit.x
	elseif pos.x > self.camera_up_limit.x then
		pos.x = self.camera_up_limit.x
	end
	if pos.y < self.camera_down_limit.y then
		pos.y = self.camera_down_limit.y
	elseif pos.y > self.camera_up_limit.y then
		pos.y = self.camera_up_limit.y
	end
	return pos
end

function update(self, dt)
	if self.gui_click then
		self.gui_click = false
		self.moving_camera = false
		self.camera_move_dir = vmath.vector3()
		self.try_selecting = false
		return
	end
	if self.zoom_delay > 0 then
		self.zoom_delay = self.zoom_delay - dt
	end
	if self.moving_camera then
		local pos = go.get_position()
		pos = pos + self.camera_move_dir * self.camera_move_speed * dt
		pos = pos - self.camera_drag_delta

		go.set_position(impose_camera_limits(self, pos))
		-- print("setting came pos to " .. pos)
	end

	if self.try_selecting then
		if not try_selecting(self, "label", 28) then
			try_selecting(self, "port", 105)
		end
		self.try_selecting = false
	end

	self.moving_camera = false
	self.camera_move_dir = vmath.vector3()
end

function on_message(self, message_id, message, sender)
	if message_id == hash("take_focus") then
		msg.post(".", "acquire_input_focus")
	elseif message_id == hash("release_focus") then
		msg.post(".", "release_input_focus")
	elseif message_id == hash("animate_camera_to") then
		local point = impose_camera_limits(self, (message.point * self.zoom) - (SCREEN_SIZE / 2 ))
		point.z = go.get_position().z
		go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, point, go.EASING_LINEAR, utils.ANIMATION_TIME)
	elseif message_id == hash('gui_click') then
		self.gui_click = true
	elseif message_id == hash('set_screen_size') then
		SCREEN_SIZE = message.size
	end
end

local function add_zoom(self)
	if self.zoom < 2 then
		self.zoom = self.zoom + .1
		set_map_scale(self)
		-- go.animate("/map", "scale", go.PLAYBACK_ONCE_FORWARD, self.zoom, go.EASING_LINEAR, .3)
		local pos = go.get_position()
		self.camera_drag_delta = vmath.vector3(-60,-(pos.y/10),0)
		self.moving_camera = true
		update_camera_limits(self)
	end
end

local function reduce_zoom(self)
	if self.zoom > 1 then
		self.zoom = self.zoom - .1
		set_map_scale(self)
		-- go.animate("/map", "scale", go.PLAYBACK_ONCE_FORWARD, self.zoom, go.EASING_LINEAR, .3)
		local pos = go.get_position()
		self.camera_drag_delta = vmath.vector3(60,(pos.y/10),0)
		self.moving_camera = true
		update_camera_limits(self)
	end
end

function on_input(self, action_id, action)
	if not action_id then
		-- self.mouse_last_pos = action
		-- print(action.x .. " " .. action.y)
	elseif action_id == hash("camera_up") then
		self.camera_move_dir.y = 1
	elseif action_id == hash("camera_down") then
		self.camera_move_dir.y = -1
	elseif action_id == hash("camera_left") then
		self.camera_move_dir.x = -1
	elseif action_id == hash("camera_right") then
		self.camera_move_dir.x = 1
	elseif action_id == hash("touch") and action.pressed then
		self.to.x = action.x
		self.to.y = action.y
		self.mouse_pressed = true
		self.try_selecting = true
	elseif action_id == hash("touch") and self.mouse_pressed and (action.dx ~= 0 or action.dy ~= 0) and not action.released then
		-- print("drag delta " .. action.dx .. " " .. action.dy)
		self.moving_camera = true
		self.camera_drag_delta = vmath.vector3(action.dx, action.dy, 0)
	elseif action_id == hash("touch") and action.released then
		self.mouse_pressed = false
	elseif action_id == hash("zoom_in") then
		-- go.animate("/map", "scale", go.PLAYBACK_ONCE_FORWARD, add_zoom(self), go.EASING_LINEAR, .5)
		add_zoom(self)
	elseif action_id == hash("zoom_out") then
		-- go.animate("/map", "scale", go.PLAYBACK_ONCE_FORWARD, reduce_zoom(self), go.EASING_LINEAR, .5)
		reduce_zoom(self)
	elseif action_id == hash("touch_multi") then
		if #action.touch > 1 then
			if #self.m_touch == 0 then
				self.m_touch[1] = action.touch[1]
				self.m_touch[2] = action.touch[2]
				self.zoom_delay = 0.1
			elseif self.zoom_delay < 0 then
				local prev_len = vmath.length(vmath.vector3(self.m_touch[2].x, self.m_touch[2].y, 0) - vmath.vector3(self.m_touch[1].x, self.m_touch[1].y, 0))
				local cur_len = vmath.length(vmath.vector3(action.touch[2].x, action.touch[2].y, 0) - vmath.vector3(action.touch[1].x, action.touch[1].y, 0))
				if prev_len > cur_len then
					reduce_zoom(self)
				else 
					add_zoom(self)
				end
				self.m_touch = {}
				self.zoom_delay = 0
			end
		end
	end

	if vmath.length(self.camera_move_dir) > 0 then
		self.moving_camera = true
		self.dir = vmath.normalize(self.camera_move_dir) 
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
