local map_ = require "main/map"
local labels = require "main/labels"

function init(self)
	labels:init()
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

-- function update(self, dt)
-- 	-- Add update code here
-- 	-- Learn more: https://defold.com/manuals/script/
-- 	-- Remove this function if not needed
-- end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if message_id == hash("set_units") then
		map_:set_units(message.tile_num, message.units)
	elseif message_id == hash("select_label") then
		map_:select_label(message.id)
	elseif message_id == hash("add_order") then
		map_:add_order(message)
	elseif message_id == hash("remove_order") then
		map_:remove_order(message.tile_num)
	elseif message_id == hash("move_camera_to_house") then
		local center = map_:get_center_of_territories(message.house)
		msg.post("/camera", "animate_camera_to", {point = center})
	elseif message_id == hash("move_camera_to_label") then
		local label_hash = hash(labels.LABEL_IDS[tonumber(message.tile_num)])
		local center = go.get_position(label_hash)
		center.z = go.get_position("/camera").z
		map_:select_label(label_hash)
		msg.post("/camera", "animate_camera_to", {point = center})
	elseif message_id == hash("set_phase") then
		map_:set_phase(message.phase)
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
