local utils = require "main/utils"

go.property("house", hash("lion"))
go.property("type", hash("support"))
go.property("number", 1)

local props = {
	star_pos = {
		consolidate = vmath.vector3(0, -16, 0),
		raid = vmath.vector3(-12, 7, 0),
		march = vmath.vector3(15, 2, 0),
		defend = vmath.vector3(14, 8, 0),
		support = vmath.vector3(-16, -8, 0),
	},
	num_pos = {
		march = vmath.vector3(9, -12, 0),
		defend = vmath.vector3(13, -7, 0),
		support = vmath.vector3(0, -15, 0),
	}
}

function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	local my_url = msg.url()
	local inst_url = tostring(my_url.path):match("%[(/%w+%d+/)")
	local star_url = inst_url .. "star"
	if self.number == 3 then
		go.set_position(props.star_pos[utils.ORDERS[self.type]], star_url)
	else
		go.set_position(vmath.vector3(0,0,-1), star_url)
	end
	local number_url = inst_url .. "number"
	if self.type == hash("march") or self.type == hash("defend") or (self.type == hash("support") and self.number == 3) then
		go.set_position(props.num_pos[utils.ORDERS[self.type]], number_url)
		if self.type ~= hash("support") then
			go.set(number_url .. "#bg", "tint", vmath.vector4(0,0,0,0))
		end
	else
		go.set_position(vmath.vector3(0,0,-1), number_url)
	end
	sprite.play_flipbook(inst_url .. "opened#order_sprite", utils.ORDERS[self.type])
	go.set_parent(nil, "/map")
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
