local utils = require "main/utils"

go.property("house", hash("lion"))
go.property("type", hash("support"))
go.property("number", 1)
go.property("is_opened", true)

go.property("star_url", false)
go.property("opened_url", false)
go.property("closed_url", false)
go.property("number_url", false)

local props = {
	star_pos = {
		[hash("consolidate")] = vmath.vector3(0, -16, 0),
		[hash("raid")] = vmath.vector3(-12, 7, 0),
		[hash("march")] = vmath.vector3(15, 2, 0),
		[hash("defend")] = vmath.vector3(14, 8, 0),
		[hash("support")] = vmath.vector3(-16, -8, 0),
	},
	num_pos = {
		[hash("march")] = vmath.vector3(9, -12, 0),
		[hash("defend")] = vmath.vector3(13, -7, 0),
		[hash("support")] = vmath.vector3(0, -15, 0),
	}
}

function on_message(self, message_id, message, sender)
	if message_id == hash("set_urls") then
		self.star_url = message.star_url
		self.opened_url = message.opened_url
		self.closed_url = message.closed_url
		self.number_url = message.number_url

		if self.number == 3 then
			go.set_position(props.star_pos[self.type], self.star_url)
		else
			go.set_position(vmath.vector3(0,0,-1), self.star_url)
		end
		-- local number_url = inst_url .. "number"
		if self.type == hash("march") or self.type == hash("defend") or (self.type == hash("support") and self.number == 3) then
			go.set_position(props.num_pos[self.type], self.number_url)
			if self.type ~= hash("support") then
				go.set(msg.url("main", self.number_url, "bg"), "tint", vmath.vector4(0,0,0,0))
				if self.type == hash("march") then
					label.set_text(msg.url("main", self.number_url, "label"), (self.number == 1 and "-1") or (self.number == 2 and "+0") or (self.number == 3 and "+1"))
				elseif self.type == hash("defend") then
					label.set_text(msg.url("main", self.number_url, "label"), ((self.number == 1 or self.number == 2) and "+1") or (self.number == 3 and "+2"))
				end
			end
		else
			go.set_position(vmath.vector3(0,0,-1), self.number_url)
		end
		sprite.play_flipbook(msg.url("main", self.opened_url, "order_sprite"), utils.ORDERS[self.type])
		sprite.play_flipbook(msg.url("main", self.closed_url, "shield_sprite"), utils.HOUSES[self.house] .. "-r")
		if not self.is_opened then
			go.set_position(vmath.vector3(0,0,0), self.opened_url)
			go.set_position(vmath.vector3(0,0,.75), self.closed_url)
		end
	end
end
