from typing import Union
from DTO.actions.planning import *
from DTO.actions.events import *
from DTO.actions.action import *

SubPhase = Union[SubPhaseSetEventCards,
        SubPhaseWildlingsDiscardHouseCard,
        SubPhaseRavenChoosePutWildlingsCardOnTopOrBottom,
        SubPhaseWildlingsChooseKill2UnitsOr2PositionsOnTrack,
        SubPhaseWildlingsMusterAtCastle,
        SubPhaseResolveConsolidatePowerOrder,
        SubPhaseMuster,
        SubPhaseDisbandUnit,
        SubPhaseCalculateCombatOutcome,
        SubPhaseCollectTaxes,
        SubPhaseAwaitingStart,
        SubPhaseRetreatUnitsAfterBattle,
        SubPhaseRavenChooseChangeOrderOrLookAtWildlingCard,
        SubPhaseCleanUpAfterRound,
        SubPhaseRecalculateSupplies,
        SubPhaseRavenChangeOrder,
        SubPhaseResolveSupportOrder,
        SubPhaseWildlingsUpgradeKnights,
        SubPhaseAutoKillUnitsAfterBattle,
        SubPhaseGetEventCards,
        SubPhaseResolveTiesAfterBiddingOnWildlings,
        SubPhaseAutoRetreatAfterBattle,
        SubPhaseChooseTracksBidsOrCollectTaxes,
        SubPhaseCleanUpAfterCombat,
        SubPhaseLeavePowerTokenAtTile,
        SubPhaseCalculateGameWinner,
        SubPhaseKillUnitsAfterBattle,
        SubPhaseResolveMarchOrder,
        SubPhaseResolveSpecialConsolidatePower,
        SubPhaseChooseToUseValyrianSteelBlade,
        SubPhaseResolveHouseCard,
        SubPhaseChooseHouseCard,
        SubPhaseDisableOrder,
        SubPhaseResolveRaidOrder,
        SubPhaseRefreshTidesOfBattleDeck,
        SubPhaseChooseDisableMarchPlus1OrDefendOrders,
        SubPhaseSetWildlingsCards,
        SubPhaseResolveTiesAfterBiddingOnTracks,
        SubPhaseWildlingsBids,
        SubPhaseReadyToOpenOrders,
        SubPhaseTracksBids,
        SubPhaseAddOrder,
        SubPhaseWildlingsKillUnits,
        SubPhaseWildlingsDowngradeKnights,
        SubPhaseSetTidesOfBattleCards,
        SubPhaseGetWildlingsCard,
        SubPhaseChooseHouseCardAfterLion5,
        SubPhaseChooseUpdateSupplyOrMuster,
        SubPhaseWildlingsChooseTrackToBeLastAt,
        SubPhaseGetTidesOfBattleCards,
        SubPhaseRavenGetWildlingsCard,
        SubPhaseWildlingsChooseTrackToBeFirstAt,
        SubPhaseWildlingsCard]
