user www-data;

events {

}

http {
    resolver 127.0.0.11 ipv6=off;
    error_log /dev/stderr debug;
    client_max_body_size 20m;

    proxy_cache_path /etc/nginx/cache keys_zone=one:500m max_size=1000m;

    server {
        listen 80;
        
        root /www/data/html/prod/htmlLaunchDir/front-defold;
        
        #index index.html;
        
        location ~ "^\/lobby\/\d+\/game\/(.*)$" {
            autoindex off;
            alias /www/data/html/prod/htmlLaunchDir/front-defold;
            try_files /$1 /index.html;
            break;
        }
        
        location / {
            try_files $uri @proxy ;
        }

        location @proxy {
            if ($request_uri ~ "^\/api\/v1(\/.*)") {
                set $url "http://web-server:80/api/v1$1";

                proxy_pass "$url";
                break;
            }

            if ($request_uri ~ "(\/.*)$") {
                alias /www/data/html/login/

                try_files /$1 /index.html;
                break;
            }
        }
    }
}
