user www-data;

events {

}

http {
    resolver 127.0.0.11 ipv6=off;
    error_log /dev/stderr debug;
    client_max_body_size 20m;

    log_format compression '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" "$gzip_ratio"';
                           
    #proxy_cache_path /etc/nginx/cache keys_zone=one:500m max_size=1000m;
    
    server {
        listen 443 ssl;
        gzip on;
        include /etc/nginx/mime.types;
        
        root /www/data/html/;
        
        #index index.html;
        
        location ~ "^\/lobby\/\d+\/game\/(.*)$" {
            autoindex off;
            alias /www/data/html/defold/htmlLaunchDir/front-defold/;
            try_files /$1 /index.html;
            break;
        }
        
        
        location /fwc {
            
            location ~ ^/fwc/api {
                try_files $uri @proxy;
            }
            
            location ~ ^/fwc(.*) {
                try_files /login/$1 /login/index.html;
            }
        }
        
        
        location /ws {
            proxy_pass http://web-server:80/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;

            break;
        }
        
       
        location = / {
            autoindex off;
            try_files /$uri /homepage/index.html;
            break;
        }
        
        location @proxy {
            if ($request_uri ~ "^\/fwc\/api\/v1(\/.*)") {
                set $url "http://web-server:80/api/v1$1";

                proxy_pass "$url";
                break;
            }
        }

        
        ssl_certificate /etc/letsencrypt/live/dmitryp.dev/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/dmitryp.dev/privkey.pem; # managed by Certbot
    }
}
