user www-data;

events {

}

http {
    resolver 127.0.0.11 ipv6=off;
    error_log /dev/stderr debug;
    client_max_body_size 20m;

    #proxy_cache_path /etc/nginx/cache keys_zone=one:500m max_size=1000m;

    server {
        listen 80;
        
        root /www/data/html/defold/htmlLaunchDir/front-defold;
        
        #index index.html;
        
        location ~ "^\/lobby\/\d+\/game\/(.*)$" {
            autoindex off;
            alias /www/data/html/defold/htmlLaunchDir/front-defold;
            try_files /$1 /index.html;
            break;
        }
        
        
        location /api {
            try_files $uri @proxy ;
        }
        
        
        location /ws {
            proxy_pass http://web-server:80/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;

            break;
        }

        location @proxy {
            if ($request_uri ~ "^\/api\/v1(\/.*)") {
                set $url "http://web-server:80/api/v1$1";

                proxy_pass "$url";
                break;
            }
        }
        
        location / {
            alias /www/data/html/login;

            try_files /$uri /index.html;
            break;
        }
    }
}
