user www-data;

events {

}

http {
    resolver 127.0.0.11 ipv6=off;
    error_log /dev/stderr debug;
    client_max_body_size 20m;

    log_format compression '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" "$gzip_ratio"';
                           
    #proxy_cache_path /etc/nginx/cache keys_zone=one:500m max_size=1000m;
    
    server {
        gzip on;
        include /etc/nginx/mime.types;
        
        root /www/data/html/;
        
        #index index.html;
        
        
        
        location /fwc {
            try_files $uri @proxy;
            break;
        }
        
        
        location /ws {
            proxy_pass http://reverse_proxy:80/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;

            break;
        }
        
        
        location @proxy {
            set $url "http://reverse_proxy:80/$uri";

            proxy_pass "$url";
            break;
        }
        
        location / {
            try_files $uri index.html;
        }

    }
}
