from typing import Union
from DTO.actions.planning import *
from DTO.actions.events import *
from DTO.actions.action import *

Action = Union[ActionRemoveOrder,
        ActionRavenChooseChangeOrderOrLookAtWildlingCard,
        ActionRavenChoosePutWildlingsCardOnTopOrBottom,
        ActionAddOrder,
        ActionRavenChangeOrder,
        ActionRavenGetWildlingsCard,
        ActionOpenOrders,
        ActionResolveCardLion1,
        ActionDisbandUnitsAfterCombat,
        ActionResolveCardMoose3,
        ActionRetreatUnitsAfterBattle,
        ActionResolveCardWolf0,
        ActionResolveCardMoose2,
        ActionUseValyrianSteelBlade,
        ActionRefreshTidesOfBattleDeck,
        ActionCleanUpAfterCombat,
        ActionResolveCardKraken6,
        ActionCalculateGameWinner,
        ActionResolveCardRose4,
        ActionChooseHouseCard,
        ActionResolveCardLion5,
        ActionResolveSupportOrder,
        ActionResolveCardPufferfish0,
        ActionCalculateCombatOutcome,
        ActionResolveConsolidatePowerOrder,
        ActionGetTidesOfBattleCards,
        ActionCleanUpAfterRound,
        ActionResolveCardRose2,
        ActionResolveSpecialConsolidatePower,
        ActionOpenTrackBids,
        ActionSetTidesOfBattleCards,
        ActionKillUnitsAfterBattle,
        ActionLeavePowerTokenAtTile,
        ActionResolveMarchOrder,
        ActionResolveRaidOrder,
        ActionChooseHouseCardAfterLion5,
        ActionWildlingsChooseTrackToBeFirstAt,
        ActionCollectTaxes,
        ActionThroneChooseSupplyOrMuster,
        ActionGetEventCards,
        ActionWildlingsChooseKill2UnitsOr2PositionsOnTrack,
        ActionResolveTiesAfterBiddingOnTracks,
        ActionResolveTiesAfterBiddingOnWildlings,
        ActionTrackBids,
        ActionWildlingsChooseTrackToBeLastAt,
        ActionStopMustering,
        ActionMuster,
        ActionWildlingsBids,
        ActionRavenChooseTrackBidsOrCollectTaxes,
        ActionWildlingsCard,
        ActionSteelBladeChooseDisableMarchOrDefend,
        ActionRecalculateSupplies,
        ActionWildlingsDiscardHouseCard,
        ActionSetEventCards,
        ActionWildlingsMusterAtCastle,
        ActionWildlingsKillUnit,
        ActionSetWildlingsCard,
        ActionDisbandUnitDueToSupplies,
        ActionGetWildlingsCard,
        ActionWildlingsReturnHouseCard,
        ActionWildlingsDowngradeKnights,
        ActionWildlingsUpgradeKnights,
        ActionDisableOrder]
